#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 22 19:08:06 2018

@author: jj
"""

import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like
import pandas_datareader.data as web
from datetime import datetime
import numpy as np


class LogisticRegression():
    
    def __init__(self):
        pass

    def sigmoid(self, x):
        return 1. / (1. + np.exp(-x))
    
    def partial_b(self, m,b,x,y):
        
        mse = 0.0
        
        for i,element in enumerate(x):
            
            mse = mse + (y[i] - (m * element + b) )
            
        return mse  / float(len(x)) 
    
    def partial_m(self,m,b,x,y):
        
        mse = 0.0
        
        for i,element in enumerate(x):
            
            mse = mse + (y[i] - (m * element + b) ) * element
            
        return mse  / float(len(x))    
    
    def cost_function(self,m,b,x,y):
        mse = 0.0
        
        for i,element in enumerate(x):
            
            mse = mse + (y[i] - (m * element + b) )**2
            
        return mse  / float(2 * len(x))


if __name__ == '__main__':
    
    start = datetime(2017, 9, 1)
    end = datetime(2018, 9, 1)
    
    stocks = ['TSLA', 'SPY']
    
    df = pd.DataFrame()
    
    for stock in stocks:
        add = web.DataReader('F', 'iex', start, end)['close']
        add = add.to_frame(name = stock)
        if df.empty:
            df = add.copy()
        else:
            df = pd.concat([df, add], axis = 1)
            
    df.index = pd.to_datetime(df.index)
    df = df.pct_change()[1:]
    print(df.head(10))
    
    #does the previous day sign predict the next day of trading?
    
    df[df >= 0.0] = 1.0
    df[df < 0.0] = 0
    
    